# Unique identifier for this project in SonarQube
sonar.projectKey=growwkey
sonar.projectName=groww

# Point to your SonarQube server IP
sonar.host.url=http://16.171.59.94:9000

# Tell SonarQube where the source code is
sonar.sources=.

# Exclude things that don't need scanning
sonar.exclusions=**/venv/**,**/charts/**,**/*.db