replicaCount: 1 # Must be 1 to prevent SQLite file conflicts
image:
  repository: mshaan/groww # Update this to your actual image!
  tag: "latest"
service:
  type: LoadBalancer
  port: 80
  targetPort: 5005