replicaCount: 2 # Must be 1 to prevent SQLite file conflicts
image:
  repository: mshaan/groww # Update this to your actual image!
  tag: "35bf12e8d7f514c31bb227b123c354a980c6f3d6"
service:
  type: LoadBalancer
  port: 80
  targetPort: 5005